name: poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  mockito: ^5.4.4
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  sizer: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/
